[package]
name = "language_server"
version = "0.1.0"
edition = "2021"

[dependencies]
parser = { path = "../parser", version = "0.1" }
serde = { version = "1.0", features = ["derive"] }
serde_json = "1.0"
thiserror = "1.0"
