#include "tree_sitter/parser.h"

#if defined(__GNUC__) || defined(__clang__)
#pragma GCC diagnostic ignored "-Wmissing-field-initializers"
#endif

#define LANGUAGE_VERSION 14
#define STATE_COUNT 69
#define LARGE_STATE_COUNT 14
#define SYMBOL_COUNT 33
#define ALIAS_COUNT 0
#define TOKEN_COUNT 21
#define EXTERNAL_TOKEN_COUNT 0
#define FIELD_COUNT 4
#define MAX_ALIAS_SEQUENCE_LENGTH 5
#define PRODUCTION_ID_COUNT 3

enum ts_symbol_identifiers {
  sym_identifier = 1,
  anon_sym_LF = 2,
  anon_sym_NULL = 3,
  anon_sym_BANG = 4,
  anon_sym_DASH = 5,
  anon_sym_LBRACK = 6,
  anon_sym_RBRACK = 7,
  anon_sym_COMMA = 8,
  anon_sym_LBRACE = 9,
  anon_sym_RBRACE = 10,
  anon_sym_COLON = 11,
  anon_sym_DQUOTE = 12,
  anon_sym_DQUOTE2 = 13,
  sym__string_basic_content = 14,
  sym_escape_sequence = 15,
  sym_integer = 16,
  sym_float = 17,
  sym_true = 18,
  sym_false = 19,
  sym_null = 20,
  sym_source_file = 21,
  sym__rules = 22,
  sym__expression = 23,
  sym_prefix_expression = 24,
  sym_array = 25,
  sym_dictionary = 26,
  sym_dictionary_pair = 27,
  sym_string = 28,
  aux_sym_source_file_repeat1 = 29,
  aux_sym_array_repeat1 = 30,
  aux_sym_dictionary_repeat1 = 31,
  aux_sym_string_repeat1 = 32,
};

static const char * const ts_symbol_names[] = {
  [ts_builtin_sym_end] = "end",
  [sym_identifier] = "identifier",
  [anon_sym_LF] = "\n",
  [anon_sym_NULL] = "\0",
  [anon_sym_BANG] = "!",
  [anon_sym_DASH] = "-",
  [anon_sym_LBRACK] = "[",
  [anon_sym_RBRACK] = "]",
  [anon_sym_COMMA] = ",",
  [anon_sym_LBRACE] = "{",
  [anon_sym_RBRACE] = "}",
  [anon_sym_COLON] = ":",
  [anon_sym_DQUOTE] = "\"",
  [anon_sym_DQUOTE2] = "\"",
  [sym__string_basic_content] = "_string_basic_content",
  [sym_escape_sequence] = "escape_sequence",
  [sym_integer] = "integer",
  [sym_float] = "float",
  [sym_true] = "true",
  [sym_false] = "false",
  [sym_null] = "null",
  [sym_source_file] = "source_file",
  [sym__rules] = "_rules",
  [sym__expression] = "_expression",
  [sym_prefix_expression] = "prefix_expression",
  [sym_array] = "array",
  [sym_dictionary] = "dictionary",
  [sym_dictionary_pair] = "dictionary_pair",
  [sym_string] = "string",
  [aux_sym_source_file_repeat1] = "source_file_repeat1",
  [aux_sym_array_repeat1] = "array_repeat1",
  [aux_sym_dictionary_repeat1] = "dictionary_repeat1",
  [aux_sym_string_repeat1] = "string_repeat1",
};

static const TSSymbol ts_symbol_map[] = {
  [ts_builtin_sym_end] = ts_builtin_sym_end,
  [sym_identifier] = sym_identifier,
  [anon_sym_LF] = anon_sym_LF,
  [anon_sym_NULL] = anon_sym_NULL,
  [anon_sym_BANG] = anon_sym_BANG,
  [anon_sym_DASH] = anon_sym_DASH,
  [anon_sym_LBRACK] = anon_sym_LBRACK,
  [anon_sym_RBRACK] = anon_sym_RBRACK,
  [anon_sym_COMMA] = anon_sym_COMMA,
  [anon_sym_LBRACE] = anon_sym_LBRACE,
  [anon_sym_RBRACE] = anon_sym_RBRACE,
  [anon_sym_COLON] = anon_sym_COLON,
  [anon_sym_DQUOTE] = anon_sym_DQUOTE,
  [anon_sym_DQUOTE2] = anon_sym_DQUOTE,
  [sym__string_basic_content] = sym__string_basic_content,
  [sym_escape_sequence] = sym_escape_sequence,
  [sym_integer] = sym_integer,
  [sym_float] = sym_float,
  [sym_true] = sym_true,
  [sym_false] = sym_false,
  [sym_null] = sym_null,
  [sym_source_file] = sym_source_file,
  [sym__rules] = sym__rules,
  [sym__expression] = sym__expression,
  [sym_prefix_expression] = sym_prefix_expression,
  [sym_array] = sym_array,
  [sym_dictionary] = sym_dictionary,
  [sym_dictionary_pair] = sym_dictionary_pair,
  [sym_string] = sym_string,
  [aux_sym_source_file_repeat1] = aux_sym_source_file_repeat1,
  [aux_sym_array_repeat1] = aux_sym_array_repeat1,
  [aux_sym_dictionary_repeat1] = aux_sym_dictionary_repeat1,
  [aux_sym_string_repeat1] = aux_sym_string_repeat1,
};

static const TSSymbolMetadata ts_symbol_metadata[] = {
  [ts_builtin_sym_end] = {
    .visible = false,
    .named = true,
  },
  [sym_identifier] = {
    .visible = true,
    .named = true,
  },
  [anon_sym_LF] = {
    .visible = true,
    .named = false,
  },
  [anon_sym_NULL] = {
    .visible = true,
    .named = false,
  },
  [anon_sym_BANG] = {
    .visible = true,
    .named = false,
  },
  [anon_sym_DASH] = {
    .visible = true,
    .named = false,
  },
  [anon_sym_LBRACK] = {
    .visible = true,
    .named = false,
  },
  [anon_sym_RBRACK] = {
    .visible = true,
    .named = false,
  },
  [anon_sym_COMMA] = {
    .visible = true,
    .named = false,
  },
  [anon_sym_LBRACE] = {
    .visible = true,
    .named = false,
  },
  [anon_sym_RBRACE] = {
    .visible = true,
    .named = false,
  },
  [anon_sym_COLON] = {
    .visible = true,
    .named = false,
  },
  [anon_sym_DQUOTE] = {
    .visible = true,
    .named = false,
  },
  [anon_sym_DQUOTE2] = {
    .visible = true,
    .named = false,
  },
  [sym__string_basic_content] = {
    .visible = false,
    .named = true,
  },
  [sym_escape_sequence] = {
    .visible = true,
    .named = true,
  },
  [sym_integer] = {
    .visible = true,
    .named = true,
  },
  [sym_float] = {
    .visible = true,
    .named = true,
  },
  [sym_true] = {
    .visible = true,
    .named = true,
  },
  [sym_false] = {
    .visible = true,
    .named = true,
  },
  [sym_null] = {
    .visible = true,
    .named = true,
  },
  [sym_source_file] = {
    .visible = true,
    .named = true,
  },
  [sym__rules] = {
    .visible = false,
    .named = true,
  },
  [sym__expression] = {
    .visible = false,
    .named = true,
  },
  [sym_prefix_expression] = {
    .visible = true,
    .named = true,
  },
  [sym_array] = {
    .visible = true,
    .named = true,
  },
  [sym_dictionary] = {
    .visible = true,
    .named = true,
  },
  [sym_dictionary_pair] = {
    .visible = true,
    .named = true,
  },
  [sym_string] = {
    .visible = true,
    .named = true,
  },
  [aux_sym_source_file_repeat1] = {
    .visible = false,
    .named = false,
  },
  [aux_sym_array_repeat1] = {
    .visible = false,
    .named = false,
  },
  [aux_sym_dictionary_repeat1] = {
    .visible = false,
    .named = false,
  },
  [aux_sym_string_repeat1] = {
    .visible = false,
    .named = false,
  },
};

enum ts_field_identifiers {
  field_key = 1,
  field_operator = 2,
  field_right = 3,
  field_value = 4,
};

static const char * const ts_field_names[] = {
  [0] = NULL,
  [field_key] = "key",
  [field_operator] = "operator",
  [field_right] = "right",
  [field_value] = "value",
};

static const TSFieldMapSlice ts_field_map_slices[PRODUCTION_ID_COUNT] = {
  [1] = {.index = 0, .length = 2},
  [2] = {.index = 2, .length = 2},
};

static const TSFieldMapEntry ts_field_map_entries[] = {
  [0] =
    {field_operator, 0},
    {field_right, 1},
  [2] =
    {field_key, 0},
    {field_value, 2},
};

static const TSSymbol ts_alias_sequences[PRODUCTION_ID_COUNT][MAX_ALIAS_SEQUENCE_LENGTH] = {
  [0] = {0},
};

static const uint16_t ts_non_terminal_alias_map[] = {
  0,
};

static const TSStateId ts_primary_state_ids[STATE_COUNT] = {
  [0] = 0,
  [1] = 1,
  [2] = 2,
  [3] = 3,
  [4] = 4,
  [5] = 2,
  [6] = 6,
  [7] = 7,
  [8] = 8,
  [9] = 6,
  [10] = 7,
  [11] = 11,
  [12] = 12,
  [13] = 11,
  [14] = 14,
  [15] = 15,
  [16] = 14,
  [17] = 17,
  [18] = 18,
  [19] = 19,
  [20] = 20,
  [21] = 17,
  [22] = 20,
  [23] = 23,
  [24] = 23,
  [25] = 19,
  [26] = 26,
  [27] = 27,
  [28] = 28,
  [29] = 29,
  [30] = 30,
  [31] = 31,
  [32] = 32,
  [33] = 33,
  [34] = 34,
  [35] = 30,
  [36] = 36,
  [37] = 31,
  [38] = 38,
  [39] = 39,
  [40] = 40,
  [41] = 41,
  [42] = 42,
  [43] = 43,
  [44] = 34,
  [45] = 36,
  [46] = 40,
  [47] = 33,
  [48] = 48,
  [49] = 39,
  [50] = 50,
  [51] = 28,
  [52] = 52,
  [53] = 43,
  [54] = 41,
  [55] = 55,
  [56] = 29,
  [57] = 57,
  [58] = 58,
  [59] = 55,
  [60] = 38,
  [61] = 42,
  [62] = 48,
  [63] = 58,
  [64] = 57,
  [65] = 65,
  [66] = 66,
  [67] = 67,
  [68] = 68,
};

static bool ts_lex(TSLexer *lexer, TSStateId state) {
  START_LEXER();
  eof = lexer->eof(lexer);
  switch (state) {
    case 0:
      if (eof) ADVANCE(7);
      ADVANCE_MAP(
        0, 9,
        '!', 10,
        '"', 19,
        ',', 14,
        '-', 11,
        ':', 17,
        '[', 12,
        '\\', 4,
        ']', 13,
        '{', 15,
        '}', 16,
      );
      if (('\t' <= lookahead && lookahead <= '\r') ||
          lookahead == ' ') SKIP(5);
      if (('0' <= lookahead && lookahead <= '9')) ADVANCE(23);
      if (('A' <= lookahead && lookahead <= 'Z') ||
          ('a' <= lookahead && lookahead <= 'z')) ADVANCE(22);
      END_STATE();
    case 1:
      if ((!eof && lookahead == 00)) ADVANCE(9);
      if (lookahead == '\n') ADVANCE(8);
      if (('\t' <= lookahead && lookahead <= '\r') ||
          lookahead == ' ') SKIP(1);
      END_STATE();
    case 2:
      if (lookahead == '"') ADVANCE(19);
      if (lookahead == '\\') ADVANCE(4);
      if (lookahead != 0 &&
          lookahead != '\n') ADVANCE(20);
      END_STATE();
    case 3:
      if (('0' <= lookahead && lookahead <= '9')) ADVANCE(24);
      END_STATE();
    case 4:
      if (lookahead != 0 &&
          lookahead != '\n') ADVANCE(21);
      END_STATE();
    case 5:
      if (eof) ADVANCE(7);
      ADVANCE_MAP(
        0, 9,
        '!', 10,
        '"', 18,
        ',', 14,
        '-', 11,
        ':', 17,
        '[', 12,
        ']', 13,
        '{', 15,
        '}', 16,
      );
      if (('\t' <= lookahead && lookahead <= '\r') ||
          lookahead == ' ') SKIP(5);
      if (('0' <= lookahead && lookahead <= '9')) ADVANCE(23);
      if (('A' <= lookahead && lookahead <= 'Z') ||
          ('a' <= lookahead && lookahead <= 'z')) ADVANCE(22);
      END_STATE();
    case 6:
      if (eof) ADVANCE(7);
      if (lookahead == '!') ADVANCE(10);
      if (lookahead == '"') ADVANCE(18);
      if (lookahead == '-') ADVANCE(11);
      if (lookahead == '[') ADVANCE(12);
      if (lookahead == ']') ADVANCE(13);
      if (lookahead == '{') ADVANCE(15);
      if (lookahead == '}') ADVANCE(16);
      if (('\t' <= lookahead && lookahead <= '\r') ||
          lookahead == ' ') SKIP(6);
      if (('0' <= lookahead && lookahead <= '9')) ADVANCE(23);
      if (('A' <= lookahead && lookahead <= 'Z') ||
          ('a' <= lookahead && lookahead <= 'z')) ADVANCE(22);
      END_STATE();
    case 7:
      ACCEPT_TOKEN(ts_builtin_sym_end);
      END_STATE();
    case 8:
      ACCEPT_TOKEN(anon_sym_LF);
      if (lookahead == '\n') ADVANCE(8);
      END_STATE();
    case 9:
      ACCEPT_TOKEN(anon_sym_NULL);
      END_STATE();
    case 10:
      ACCEPT_TOKEN(anon_sym_BANG);
      END_STATE();
    case 11:
      ACCEPT_TOKEN(anon_sym_DASH);
      END_STATE();
    case 12:
      ACCEPT_TOKEN(anon_sym_LBRACK);
      END_STATE();
    case 13:
      ACCEPT_TOKEN(anon_sym_RBRACK);
      END_STATE();
    case 14:
      ACCEPT_TOKEN(anon_sym_COMMA);
      END_STATE();
    case 15:
      ACCEPT_TOKEN(anon_sym_LBRACE);
      END_STATE();
    case 16:
      ACCEPT_TOKEN(anon_sym_RBRACE);
      END_STATE();
    case 17:
      ACCEPT_TOKEN(anon_sym_COLON);
      END_STATE();
    case 18:
      ACCEPT_TOKEN(anon_sym_DQUOTE);
      END_STATE();
    case 19:
      ACCEPT_TOKEN(anon_sym_DQUOTE2);
      END_STATE();
    case 20:
      ACCEPT_TOKEN(sym__string_basic_content);
      if (lookahead != 0 &&
          lookahead != '\n' &&
          lookahead != '"' &&
          lookahead != '\\') ADVANCE(20);
      END_STATE();
    case 21:
      ACCEPT_TOKEN(sym_escape_sequence);
      END_STATE();
    case 22:
      ACCEPT_TOKEN(sym_identifier);
      if (('0' <= lookahead && lookahead <= '9') ||
          ('A' <= lookahead && lookahead <= 'Z') ||
          lookahead == '_' ||
          ('a' <= lookahead && lookahead <= 'z')) ADVANCE(22);
      END_STATE();
    case 23:
      ACCEPT_TOKEN(sym_integer);
      if (lookahead == '.') ADVANCE(3);
      if (('0' <= lookahead && lookahead <= '9')) ADVANCE(23);
      END_STATE();
    case 24:
      ACCEPT_TOKEN(sym_float);
      if (('0' <= lookahead && lookahead <= '9')) ADVANCE(24);
      END_STATE();
    default:
      return false;
  }
}

static bool ts_lex_keywords(TSLexer *lexer, TSStateId state) {
  START_LEXER();
  eof = lexer->eof(lexer);
  switch (state) {
    case 0:
      if (lookahead == 'f') ADVANCE(1);
      if (lookahead == 'n') ADVANCE(2);
      if (lookahead == 't') ADVANCE(3);
      if (('\t' <= lookahead && lookahead <= '\r') ||
          lookahead == ' ') SKIP(0);
      END_STATE();
    case 1:
      if (lookahead == 'a') ADVANCE(4);
      END_STATE();
    case 2:
      if (lookahead == 'u') ADVANCE(5);
      END_STATE();
    case 3:
      if (lookahead == 'r') ADVANCE(6);
      END_STATE();
    case 4:
      if (lookahead == 'l') ADVANCE(7);
      END_STATE();
    case 5:
      if (lookahead == 'l') ADVANCE(8);
      END_STATE();
    case 6:
      if (lookahead == 'u') ADVANCE(9);
      END_STATE();
    case 7:
      if (lookahead == 's') ADVANCE(10);
      END_STATE();
    case 8:
      if (lookahead == 'l') ADVANCE(11);
      END_STATE();
    case 9:
      if (lookahead == 'e') ADVANCE(12);
      END_STATE();
    case 10:
      if (lookahead == 'e') ADVANCE(13);
      END_STATE();
    case 11:
      ACCEPT_TOKEN(sym_null);
      END_STATE();
    case 12:
      ACCEPT_TOKEN(sym_true);
      END_STATE();
    case 13:
      ACCEPT_TOKEN(sym_false);
      END_STATE();
    default:
      return false;
  }
}

static const TSLexMode ts_lex_modes[STATE_COUNT] = {
  [0] = {.lex_state = 0},
  [1] = {.lex_state = 6},
  [2] = {.lex_state = 6},
  [3] = {.lex_state = 6},
  [4] = {.lex_state = 6},
  [5] = {.lex_state = 6},
  [6] = {.lex_state = 6},
  [7] = {.lex_state = 6},
  [8] = {.lex_state = 6},
  [9] = {.lex_state = 6},
  [10] = {.lex_state = 6},
  [11] = {.lex_state = 6},
  [12] = {.lex_state = 6},
  [13] = {.lex_state = 6},
  [14] = {.lex_state = 6},
  [15] = {.lex_state = 6},
  [16] = {.lex_state = 6},
  [17] = {.lex_state = 6},
  [18] = {.lex_state = 6},
  [19] = {.lex_state = 6},
  [20] = {.lex_state = 6},
  [21] = {.lex_state = 6},
  [22] = {.lex_state = 6},
  [23] = {.lex_state = 6},
  [24] = {.lex_state = 6},
  [25] = {.lex_state = 6},
  [26] = {.lex_state = 6},
  [27] = {.lex_state = 6},
  [28] = {.lex_state = 0},
  [29] = {.lex_state = 0},
  [30] = {.lex_state = 2},
  [31] = {.lex_state = 2},
  [32] = {.lex_state = 2},
  [33] = {.lex_state = 0},
  [34] = {.lex_state = 0},
  [35] = {.lex_state = 2},
  [36] = {.lex_state = 0},
  [37] = {.lex_state = 2},
  [38] = {.lex_state = 0},
  [39] = {.lex_state = 0},
  [40] = {.lex_state = 0},
  [41] = {.lex_state = 0},
  [42] = {.lex_state = 0},
  [43] = {.lex_state = 0},
  [44] = {.lex_state = 1},
  [45] = {.lex_state = 1},
  [46] = {.lex_state = 1},
  [47] = {.lex_state = 1},
  [48] = {.lex_state = 0},
  [49] = {.lex_state = 1},
  [50] = {.lex_state = 1},
  [51] = {.lex_state = 1},
  [52] = {.lex_state = 0},
  [53] = {.lex_state = 1},
  [54] = {.lex_state = 1},
  [55] = {.lex_state = 0},
  [56] = {.lex_state = 1},
  [57] = {.lex_state = 0},
  [58] = {.lex_state = 0},
  [59] = {.lex_state = 0},
  [60] = {.lex_state = 1},
  [61] = {.lex_state = 1},
  [62] = {.lex_state = 0},
  [63] = {.lex_state = 0},
  [64] = {.lex_state = 0},
  [65] = {.lex_state = 0},
  [66] = {.lex_state = 0},
  [67] = {.lex_state = 0},
  [68] = {.lex_state = 0},
};

static const uint16_t ts_parse_table[LARGE_STATE_COUNT][SYMBOL_COUNT] = {
  [0] = {
    [ts_builtin_sym_end] = ACTIONS(1),
    [sym_identifier] = ACTIONS(1),
    [anon_sym_NULL] = ACTIONS(1),
    [anon_sym_BANG] = ACTIONS(1),
    [anon_sym_DASH] = ACTIONS(1),
    [anon_sym_LBRACK] = ACTIONS(1),
    [anon_sym_RBRACK] = ACTIONS(1),
    [anon_sym_COMMA] = ACTIONS(1),
    [anon_sym_LBRACE] = ACTIONS(1),
    [anon_sym_RBRACE] = ACTIONS(1),
    [anon_sym_COLON] = ACTIONS(1),
    [anon_sym_DQUOTE] = ACTIONS(1),
    [anon_sym_DQUOTE2] = ACTIONS(1),
    [sym_escape_sequence] = ACTIONS(1),
    [sym_integer] = ACTIONS(1),
    [sym_float] = ACTIONS(1),
    [sym_true] = ACTIONS(1),
    [sym_false] = ACTIONS(1),
    [sym_null] = ACTIONS(1),
  },
  [1] = {
    [sym_source_file] = STATE(68),
    [sym__rules] = STATE(3),
    [sym__expression] = STATE(50),
    [sym_prefix_expression] = STATE(50),
    [sym_array] = STATE(50),
    [sym_dictionary] = STATE(50),
    [sym_string] = STATE(50),
    [aux_sym_source_file_repeat1] = STATE(3),
    [ts_builtin_sym_end] = ACTIONS(3),
    [sym_identifier] = ACTIONS(5),
    [anon_sym_BANG] = ACTIONS(7),
    [anon_sym_DASH] = ACTIONS(7),
    [anon_sym_LBRACK] = ACTIONS(9),
    [anon_sym_LBRACE] = ACTIONS(11),
    [anon_sym_DQUOTE] = ACTIONS(13),
    [sym_integer] = ACTIONS(5),
    [sym_float] = ACTIONS(15),
    [sym_true] = ACTIONS(5),
    [sym_false] = ACTIONS(5),
    [sym_null] = ACTIONS(5),
  },
  [2] = {
    [sym__expression] = STATE(65),
    [sym_prefix_expression] = STATE(65),
    [sym_array] = STATE(65),
    [sym_dictionary] = STATE(65),
    [sym_dictionary_pair] = STATE(55),
    [sym_string] = STATE(65),
    [aux_sym_dictionary_repeat1] = STATE(10),
    [sym_identifier] = ACTIONS(17),
    [anon_sym_BANG] = ACTIONS(19),
    [anon_sym_DASH] = ACTIONS(19),
    [anon_sym_LBRACK] = ACTIONS(21),
    [anon_sym_LBRACE] = ACTIONS(23),
    [anon_sym_RBRACE] = ACTIONS(25),
    [anon_sym_DQUOTE] = ACTIONS(27),
    [sym_integer] = ACTIONS(17),
    [sym_float] = ACTIONS(29),
    [sym_true] = ACTIONS(17),
    [sym_false] = ACTIONS(17),
    [sym_null] = ACTIONS(17),
  },
  [3] = {
    [sym__rules] = STATE(4),
    [sym__expression] = STATE(50),
    [sym_prefix_expression] = STATE(50),
    [sym_array] = STATE(50),
    [sym_dictionary] = STATE(50),
    [sym_string] = STATE(50),
    [aux_sym_source_file_repeat1] = STATE(4),
    [ts_builtin_sym_end] = ACTIONS(31),
    [sym_identifier] = ACTIONS(5),
    [anon_sym_BANG] = ACTIONS(7),
    [anon_sym_DASH] = ACTIONS(7),
    [anon_sym_LBRACK] = ACTIONS(9),
    [anon_sym_LBRACE] = ACTIONS(11),
    [anon_sym_DQUOTE] = ACTIONS(13),
    [sym_integer] = ACTIONS(5),
    [sym_float] = ACTIONS(15),
    [sym_true] = ACTIONS(5),
    [sym_false] = ACTIONS(5),
    [sym_null] = ACTIONS(5),
  },
  [4] = {
    [sym__rules] = STATE(4),
    [sym__expression] = STATE(50),
    [sym_prefix_expression] = STATE(50),
    [sym_array] = STATE(50),
    [sym_dictionary] = STATE(50),
    [sym_string] = STATE(50),
    [aux_sym_source_file_repeat1] = STATE(4),
    [ts_builtin_sym_end] = ACTIONS(33),
    [sym_identifier] = ACTIONS(35),
    [anon_sym_BANG] = ACTIONS(38),
    [anon_sym_DASH] = ACTIONS(38),
    [anon_sym_LBRACK] = ACTIONS(41),
    [anon_sym_LBRACE] = ACTIONS(44),
    [anon_sym_DQUOTE] = ACTIONS(47),
    [sym_integer] = ACTIONS(35),
    [sym_float] = ACTIONS(50),
    [sym_true] = ACTIONS(35),
    [sym_false] = ACTIONS(35),
    [sym_null] = ACTIONS(35),
  },
  [5] = {
    [sym__expression] = STATE(65),
    [sym_prefix_expression] = STATE(65),
    [sym_array] = STATE(65),
    [sym_dictionary] = STATE(65),
    [sym_dictionary_pair] = STATE(59),
    [sym_string] = STATE(65),
    [aux_sym_dictionary_repeat1] = STATE(7),
    [sym_identifier] = ACTIONS(17),
    [anon_sym_BANG] = ACTIONS(19),
    [anon_sym_DASH] = ACTIONS(19),
    [anon_sym_LBRACK] = ACTIONS(21),
    [anon_sym_LBRACE] = ACTIONS(23),
    [anon_sym_RBRACE] = ACTIONS(53),
    [anon_sym_DQUOTE] = ACTIONS(27),
    [sym_integer] = ACTIONS(17),
    [sym_float] = ACTIONS(29),
    [sym_true] = ACTIONS(17),
    [sym_false] = ACTIONS(17),
    [sym_null] = ACTIONS(17),
  },
  [6] = {
    [sym__expression] = STATE(63),
    [sym_prefix_expression] = STATE(63),
    [sym_array] = STATE(63),
    [sym_dictionary] = STATE(63),
    [sym_string] = STATE(63),
    [aux_sym_array_repeat1] = STATE(13),
    [sym_identifier] = ACTIONS(55),
    [anon_sym_BANG] = ACTIONS(19),
    [anon_sym_DASH] = ACTIONS(19),
    [anon_sym_LBRACK] = ACTIONS(21),
    [anon_sym_RBRACK] = ACTIONS(57),
    [anon_sym_LBRACE] = ACTIONS(23),
    [anon_sym_DQUOTE] = ACTIONS(27),
    [sym_integer] = ACTIONS(55),
    [sym_float] = ACTIONS(59),
    [sym_true] = ACTIONS(55),
    [sym_false] = ACTIONS(55),
    [sym_null] = ACTIONS(55),
  },
  [7] = {
    [sym__expression] = STATE(65),
    [sym_prefix_expression] = STATE(65),
    [sym_array] = STATE(65),
    [sym_dictionary] = STATE(65),
    [sym_dictionary_pair] = STATE(64),
    [sym_string] = STATE(65),
    [aux_sym_dictionary_repeat1] = STATE(8),
    [sym_identifier] = ACTIONS(17),
    [anon_sym_BANG] = ACTIONS(19),
    [anon_sym_DASH] = ACTIONS(19),
    [anon_sym_LBRACK] = ACTIONS(21),
    [anon_sym_LBRACE] = ACTIONS(23),
    [anon_sym_DQUOTE] = ACTIONS(27),
    [sym_integer] = ACTIONS(17),
    [sym_float] = ACTIONS(29),
    [sym_true] = ACTIONS(17),
    [sym_false] = ACTIONS(17),
    [sym_null] = ACTIONS(17),
  },
  [8] = {
    [sym__expression] = STATE(65),
    [sym_prefix_expression] = STATE(65),
    [sym_array] = STATE(65),
    [sym_dictionary] = STATE(65),
    [sym_dictionary_pair] = STATE(67),
    [sym_string] = STATE(65),
    [aux_sym_dictionary_repeat1] = STATE(8),
    [sym_identifier] = ACTIONS(61),
    [anon_sym_BANG] = ACTIONS(64),
    [anon_sym_DASH] = ACTIONS(64),
    [anon_sym_LBRACK] = ACTIONS(67),
    [anon_sym_LBRACE] = ACTIONS(70),
    [anon_sym_DQUOTE] = ACTIONS(73),
    [sym_integer] = ACTIONS(61),
    [sym_float] = ACTIONS(76),
    [sym_true] = ACTIONS(61),
    [sym_false] = ACTIONS(61),
    [sym_null] = ACTIONS(61),
  },
  [9] = {
    [sym__expression] = STATE(58),
    [sym_prefix_expression] = STATE(58),
    [sym_array] = STATE(58),
    [sym_dictionary] = STATE(58),
    [sym_string] = STATE(58),
    [aux_sym_array_repeat1] = STATE(11),
    [sym_identifier] = ACTIONS(79),
    [anon_sym_BANG] = ACTIONS(19),
    [anon_sym_DASH] = ACTIONS(19),
    [anon_sym_LBRACK] = ACTIONS(21),
    [anon_sym_RBRACK] = ACTIONS(81),
    [anon_sym_LBRACE] = ACTIONS(23),
    [anon_sym_DQUOTE] = ACTIONS(27),
    [sym_integer] = ACTIONS(79),
    [sym_float] = ACTIONS(83),
    [sym_true] = ACTIONS(79),
    [sym_false] = ACTIONS(79),
    [sym_null] = ACTIONS(79),
  },
  [10] = {
    [sym__expression] = STATE(65),
    [sym_prefix_expression] = STATE(65),
    [sym_array] = STATE(65),
    [sym_dictionary] = STATE(65),
    [sym_dictionary_pair] = STATE(57),
    [sym_string] = STATE(65),
    [aux_sym_dictionary_repeat1] = STATE(8),
    [sym_identifier] = ACTIONS(17),
    [anon_sym_BANG] = ACTIONS(19),
    [anon_sym_DASH] = ACTIONS(19),
    [anon_sym_LBRACK] = ACTIONS(21),
    [anon_sym_LBRACE] = ACTIONS(23),
    [anon_sym_DQUOTE] = ACTIONS(27),
    [sym_integer] = ACTIONS(17),
    [sym_float] = ACTIONS(29),
    [sym_true] = ACTIONS(17),
    [sym_false] = ACTIONS(17),
    [sym_null] = ACTIONS(17),
  },
  [11] = {
    [sym__expression] = STATE(62),
    [sym_prefix_expression] = STATE(62),
    [sym_array] = STATE(62),
    [sym_dictionary] = STATE(62),
    [sym_string] = STATE(62),
    [aux_sym_array_repeat1] = STATE(12),
    [sym_identifier] = ACTIONS(85),
    [anon_sym_BANG] = ACTIONS(19),
    [anon_sym_DASH] = ACTIONS(19),
    [anon_sym_LBRACK] = ACTIONS(21),
    [anon_sym_LBRACE] = ACTIONS(23),
    [anon_sym_DQUOTE] = ACTIONS(27),
    [sym_integer] = ACTIONS(85),
    [sym_float] = ACTIONS(87),
    [sym_true] = ACTIONS(85),
    [sym_false] = ACTIONS(85),
    [sym_null] = ACTIONS(85),
  },
  [12] = {
    [sym__expression] = STATE(66),
    [sym_prefix_expression] = STATE(66),
    [sym_array] = STATE(66),
    [sym_dictionary] = STATE(66),
    [sym_string] = STATE(66),
    [aux_sym_array_repeat1] = STATE(12),
    [sym_identifier] = ACTIONS(89),
    [anon_sym_BANG] = ACTIONS(92),
    [anon_sym_DASH] = ACTIONS(92),
    [anon_sym_LBRACK] = ACTIONS(95),
    [anon_sym_LBRACE] = ACTIONS(98),
    [anon_sym_DQUOTE] = ACTIONS(101),
    [sym_integer] = ACTIONS(89),
    [sym_float] = ACTIONS(104),
    [sym_true] = ACTIONS(89),
    [sym_false] = ACTIONS(89),
    [sym_null] = ACTIONS(89),
  },
  [13] = {
    [sym__expression] = STATE(48),
    [sym_prefix_expression] = STATE(48),
    [sym_array] = STATE(48),
    [sym_dictionary] = STATE(48),
    [sym_string] = STATE(48),
    [aux_sym_array_repeat1] = STATE(12),
    [sym_identifier] = ACTIONS(107),
    [anon_sym_BANG] = ACTIONS(19),
    [anon_sym_DASH] = ACTIONS(19),
    [anon_sym_LBRACK] = ACTIONS(21),
    [anon_sym_LBRACE] = ACTIONS(23),
    [anon_sym_DQUOTE] = ACTIONS(27),
    [sym_integer] = ACTIONS(107),
    [sym_float] = ACTIONS(109),
    [sym_true] = ACTIONS(107),
    [sym_false] = ACTIONS(107),
    [sym_null] = ACTIONS(107),
  },
};

static const uint16_t ts_small_parse_table[] = {
  [0] = 7,
    ACTIONS(9), 1,
      anon_sym_LBRACK,
    ACTIONS(11), 1,
      anon_sym_LBRACE,
    ACTIONS(13), 1,
      anon_sym_DQUOTE,
    ACTIONS(113), 1,
      sym_float,
    ACTIONS(7), 2,
      anon_sym_BANG,
      anon_sym_DASH,
    ACTIONS(111), 5,
      sym_identifier,
      sym_integer,
      sym_true,
      sym_false,
      sym_null,
    STATE(53), 5,
      sym__expression,
      sym_prefix_expression,
      sym_array,
      sym_dictionary,
      sym_string,
  [31] = 7,
    ACTIONS(21), 1,
      anon_sym_LBRACK,
    ACTIONS(23), 1,
      anon_sym_LBRACE,
    ACTIONS(27), 1,
      anon_sym_DQUOTE,
    ACTIONS(117), 1,
      sym_float,
    ACTIONS(19), 2,
      anon_sym_BANG,
      anon_sym_DASH,
    ACTIONS(115), 5,
      sym_identifier,
      sym_integer,
      sym_true,
      sym_false,
      sym_null,
    STATE(52), 5,
      sym__expression,
      sym_prefix_expression,
      sym_array,
      sym_dictionary,
      sym_string,
  [62] = 7,
    ACTIONS(21), 1,
      anon_sym_LBRACK,
    ACTIONS(23), 1,
      anon_sym_LBRACE,
    ACTIONS(27), 1,
      anon_sym_DQUOTE,
    ACTIONS(121), 1,
      sym_float,
    ACTIONS(19), 2,
      anon_sym_BANG,
      anon_sym_DASH,
    ACTIONS(119), 5,
      sym_identifier,
      sym_integer,
      sym_true,
      sym_false,
      sym_null,
    STATE(43), 5,
      sym__expression,
      sym_prefix_expression,
      sym_array,
      sym_dictionary,
      sym_string,
  [93] = 3,
    ACTIONS(127), 1,
      anon_sym_RBRACE,
    ACTIONS(123), 5,
      sym_identifier,
      sym_integer,
      sym_true,
      sym_false,
      sym_null,
    ACTIONS(125), 6,
      anon_sym_BANG,
      anon_sym_DASH,
      anon_sym_LBRACK,
      anon_sym_LBRACE,
      anon_sym_DQUOTE,
      sym_float,
  [112] = 2,
    ACTIONS(131), 5,
      sym_identifier,
      sym_integer,
      sym_true,
      sym_false,
      sym_null,
    ACTIONS(129), 7,
      ts_builtin_sym_end,
      anon_sym_BANG,
      anon_sym_DASH,
      anon_sym_LBRACK,
      anon_sym_LBRACE,
      anon_sym_DQUOTE,
      sym_float,
  [129] = 3,
    ACTIONS(137), 1,
      anon_sym_RBRACK,
    ACTIONS(133), 5,
      sym_identifier,
      sym_integer,
      sym_true,
      sym_false,
      sym_null,
    ACTIONS(135), 6,
      anon_sym_BANG,
      anon_sym_DASH,
      anon_sym_LBRACK,
      anon_sym_LBRACE,
      anon_sym_DQUOTE,
      sym_float,
  [148] = 3,
    ACTIONS(139), 1,
      anon_sym_RBRACK,
    ACTIONS(133), 5,
      sym_identifier,
      sym_integer,
      sym_true,
      sym_false,
      sym_null,
    ACTIONS(135), 6,
      anon_sym_BANG,
      anon_sym_DASH,
      anon_sym_LBRACK,
      anon_sym_LBRACE,
      anon_sym_DQUOTE,
      sym_float,
  [167] = 3,
    ACTIONS(141), 1,
      anon_sym_RBRACE,
    ACTIONS(123), 5,
      sym_identifier,
      sym_integer,
      sym_true,
      sym_false,
      sym_null,
    ACTIONS(125), 6,
      anon_sym_BANG,
      anon_sym_DASH,
      anon_sym_LBRACK,
      anon_sym_LBRACE,
      anon_sym_DQUOTE,
      sym_float,
  [186] = 3,
    ACTIONS(143), 1,
      anon_sym_RBRACK,
    ACTIONS(133), 5,
      sym_identifier,
      sym_integer,
      sym_true,
      sym_false,
      sym_null,
    ACTIONS(135), 6,
      anon_sym_BANG,
      anon_sym_DASH,
      anon_sym_LBRACK,
      anon_sym_LBRACE,
      anon_sym_DQUOTE,
      sym_float,
  [205] = 3,
    ACTIONS(145), 1,
      anon_sym_RBRACE,
    ACTIONS(123), 5,
      sym_identifier,
      sym_integer,
      sym_true,
      sym_false,
      sym_null,
    ACTIONS(125), 6,
      anon_sym_BANG,
      anon_sym_DASH,
      anon_sym_LBRACK,
      anon_sym_LBRACE,
      anon_sym_DQUOTE,
      sym_float,
  [224] = 3,
    ACTIONS(147), 1,
      anon_sym_RBRACE,
    ACTIONS(123), 5,
      sym_identifier,
      sym_integer,
      sym_true,
      sym_false,
      sym_null,
    ACTIONS(125), 6,
      anon_sym_BANG,
      anon_sym_DASH,
      anon_sym_LBRACK,
      anon_sym_LBRACE,
      anon_sym_DQUOTE,
      sym_float,
  [243] = 3,
    ACTIONS(149), 1,
      anon_sym_RBRACK,
    ACTIONS(133), 5,
      sym_identifier,
      sym_integer,
      sym_true,
      sym_false,
      sym_null,
    ACTIONS(135), 6,
      anon_sym_BANG,
      anon_sym_DASH,
      anon_sym_LBRACK,
      anon_sym_LBRACE,
      anon_sym_DQUOTE,
      sym_float,
  [262] = 2,
    ACTIONS(123), 5,
      sym_identifier,
      sym_integer,
      sym_true,
      sym_false,
      sym_null,
    ACTIONS(125), 6,
      anon_sym_BANG,
      anon_sym_DASH,
      anon_sym_LBRACK,
      anon_sym_LBRACE,
      anon_sym_DQUOTE,
      sym_float,
  [278] = 2,
    ACTIONS(133), 5,
      sym_identifier,
      sym_integer,
      sym_true,
      sym_false,
      sym_null,
    ACTIONS(135), 6,
      anon_sym_BANG,
      anon_sym_DASH,
      anon_sym_LBRACK,
      anon_sym_LBRACE,
      anon_sym_DQUOTE,
      sym_float,
  [294] = 1,
    ACTIONS(151), 4,
      anon_sym_RBRACK,
      anon_sym_COMMA,
      anon_sym_RBRACE,
      anon_sym_COLON,
  [301] = 1,
    ACTIONS(153), 4,
      anon_sym_RBRACK,
      anon_sym_COMMA,
      anon_sym_RBRACE,
      anon_sym_COLON,
  [308] = 3,
    ACTIONS(155), 1,
      anon_sym_DQUOTE2,
    STATE(32), 1,
      aux_sym_string_repeat1,
    ACTIONS(157), 2,
      sym__string_basic_content,
      sym_escape_sequence,
  [319] = 3,
    ACTIONS(159), 1,
      anon_sym_DQUOTE2,
    STATE(30), 1,
      aux_sym_string_repeat1,
    ACTIONS(161), 2,
      sym__string_basic_content,
      sym_escape_sequence,
  [330] = 3,
    ACTIONS(163), 1,
      anon_sym_DQUOTE2,
    STATE(32), 1,
      aux_sym_string_repeat1,
    ACTIONS(165), 2,
      sym__string_basic_content,
      sym_escape_sequence,
  [341] = 1,
    ACTIONS(168), 4,
      anon_sym_RBRACK,
      anon_sym_COMMA,
      anon_sym_RBRACE,
      anon_sym_COLON,
  [348] = 1,
    ACTIONS(170), 4,
      anon_sym_RBRACK,
      anon_sym_COMMA,
      anon_sym_RBRACE,
      anon_sym_COLON,
  [355] = 3,
    ACTIONS(172), 1,
      anon_sym_DQUOTE2,
    STATE(32), 1,
      aux_sym_string_repeat1,
    ACTIONS(157), 2,
      sym__string_basic_content,
      sym_escape_sequence,
  [366] = 1,
    ACTIONS(174), 4,
      anon_sym_RBRACK,
      anon_sym_COMMA,
      anon_sym_RBRACE,
      anon_sym_COLON,
  [373] = 3,
    ACTIONS(176), 1,
      anon_sym_DQUOTE2,
    STATE(35), 1,
      aux_sym_string_repeat1,
    ACTIONS(178), 2,
      sym__string_basic_content,
      sym_escape_sequence,
  [384] = 1,
    ACTIONS(180), 4,
      anon_sym_RBRACK,
      anon_sym_COMMA,
      anon_sym_RBRACE,
      anon_sym_COLON,
  [391] = 1,
    ACTIONS(182), 4,
      anon_sym_RBRACK,
      anon_sym_COMMA,
      anon_sym_RBRACE,
      anon_sym_COLON,
  [398] = 1,
    ACTIONS(184), 4,
      anon_sym_RBRACK,
      anon_sym_COMMA,
      anon_sym_RBRACE,
      anon_sym_COLON,
  [405] = 1,
    ACTIONS(186), 4,
      anon_sym_RBRACK,
      anon_sym_COMMA,
      anon_sym_RBRACE,
      anon_sym_COLON,
  [412] = 1,
    ACTIONS(188), 4,
      anon_sym_RBRACK,
      anon_sym_COMMA,
      anon_sym_RBRACE,
      anon_sym_COLON,
  [419] = 1,
    ACTIONS(190), 4,
      anon_sym_RBRACK,
      anon_sym_COMMA,
      anon_sym_RBRACE,
      anon_sym_COLON,
  [426] = 2,
    ACTIONS(170), 1,
      anon_sym_LF,
    ACTIONS(192), 1,
      anon_sym_NULL,
  [433] = 2,
    ACTIONS(174), 1,
      anon_sym_LF,
    ACTIONS(194), 1,
      anon_sym_NULL,
  [440] = 2,
    ACTIONS(184), 1,
      anon_sym_LF,
    ACTIONS(196), 1,
      anon_sym_NULL,
  [447] = 2,
    ACTIONS(168), 1,
      anon_sym_LF,
    ACTIONS(198), 1,
      anon_sym_NULL,
  [454] = 2,
    ACTIONS(139), 1,
      anon_sym_RBRACK,
    ACTIONS(200), 1,
      anon_sym_COMMA,
  [461] = 2,
    ACTIONS(182), 1,
      anon_sym_LF,
    ACTIONS(202), 1,
      anon_sym_NULL,
  [468] = 2,
    ACTIONS(204), 1,
      anon_sym_LF,
    ACTIONS(206), 1,
      anon_sym_NULL,
  [475] = 2,
    ACTIONS(151), 1,
      anon_sym_LF,
    ACTIONS(208), 1,
      anon_sym_NULL,
  [482] = 1,
    ACTIONS(210), 2,
      anon_sym_COMMA,
      anon_sym_RBRACE,
  [487] = 2,
    ACTIONS(190), 1,
      anon_sym_LF,
    ACTIONS(212), 1,
      anon_sym_NULL,
  [494] = 2,
    ACTIONS(186), 1,
      anon_sym_LF,
    ACTIONS(214), 1,
      anon_sym_NULL,
  [501] = 2,
    ACTIONS(216), 1,
      anon_sym_COMMA,
    ACTIONS(218), 1,
      anon_sym_RBRACE,
  [508] = 2,
    ACTIONS(153), 1,
      anon_sym_LF,
    ACTIONS(220), 1,
      anon_sym_NULL,
  [515] = 2,
    ACTIONS(147), 1,
      anon_sym_RBRACE,
    ACTIONS(222), 1,
      anon_sym_COMMA,
  [522] = 2,
    ACTIONS(224), 1,
      anon_sym_RBRACK,
    ACTIONS(226), 1,
      anon_sym_COMMA,
  [529] = 2,
    ACTIONS(228), 1,
      anon_sym_COMMA,
    ACTIONS(230), 1,
      anon_sym_RBRACE,
  [536] = 2,
    ACTIONS(180), 1,
      anon_sym_LF,
    ACTIONS(232), 1,
      anon_sym_NULL,
  [543] = 2,
    ACTIONS(188), 1,
      anon_sym_LF,
    ACTIONS(234), 1,
      anon_sym_NULL,
  [550] = 2,
    ACTIONS(143), 1,
      anon_sym_RBRACK,
    ACTIONS(236), 1,
      anon_sym_COMMA,
  [557] = 2,
    ACTIONS(238), 1,
      anon_sym_RBRACK,
    ACTIONS(240), 1,
      anon_sym_COMMA,
  [564] = 2,
    ACTIONS(145), 1,
      anon_sym_RBRACE,
    ACTIONS(242), 1,
      anon_sym_COMMA,
  [571] = 1,
    ACTIONS(244), 1,
      anon_sym_COLON,
  [575] = 1,
    ACTIONS(246), 1,
      anon_sym_COMMA,
  [579] = 1,
    ACTIONS(248), 1,
      anon_sym_COMMA,
  [583] = 1,
    ACTIONS(250), 1,
      ts_builtin_sym_end,
};

static const uint32_t ts_small_parse_table_map[] = {
  [SMALL_STATE(14)] = 0,
  [SMALL_STATE(15)] = 31,
  [SMALL_STATE(16)] = 62,
  [SMALL_STATE(17)] = 93,
  [SMALL_STATE(18)] = 112,
  [SMALL_STATE(19)] = 129,
  [SMALL_STATE(20)] = 148,
  [SMALL_STATE(21)] = 167,
  [SMALL_STATE(22)] = 186,
  [SMALL_STATE(23)] = 205,
  [SMALL_STATE(24)] = 224,
  [SMALL_STATE(25)] = 243,
  [SMALL_STATE(26)] = 262,
  [SMALL_STATE(27)] = 278,
  [SMALL_STATE(28)] = 294,
  [SMALL_STATE(29)] = 301,
  [SMALL_STATE(30)] = 308,
  [SMALL_STATE(31)] = 319,
  [SMALL_STATE(32)] = 330,
  [SMALL_STATE(33)] = 341,
  [SMALL_STATE(34)] = 348,
  [SMALL_STATE(35)] = 355,
  [SMALL_STATE(36)] = 366,
  [SMALL_STATE(37)] = 373,
  [SMALL_STATE(38)] = 384,
  [SMALL_STATE(39)] = 391,
  [SMALL_STATE(40)] = 398,
  [SMALL_STATE(41)] = 405,
  [SMALL_STATE(42)] = 412,
  [SMALL_STATE(43)] = 419,
  [SMALL_STATE(44)] = 426,
  [SMALL_STATE(45)] = 433,
  [SMALL_STATE(46)] = 440,
  [SMALL_STATE(47)] = 447,
  [SMALL_STATE(48)] = 454,
  [SMALL_STATE(49)] = 461,
  [SMALL_STATE(50)] = 468,
  [SMALL_STATE(51)] = 475,
  [SMALL_STATE(52)] = 482,
  [SMALL_STATE(53)] = 487,
  [SMALL_STATE(54)] = 494,
  [SMALL_STATE(55)] = 501,
  [SMALL_STATE(56)] = 508,
  [SMALL_STATE(57)] = 515,
  [SMALL_STATE(58)] = 522,
  [SMALL_STATE(59)] = 529,
  [SMALL_STATE(60)] = 536,
  [SMALL_STATE(61)] = 543,
  [SMALL_STATE(62)] = 550,
  [SMALL_STATE(63)] = 557,
  [SMALL_STATE(64)] = 564,
  [SMALL_STATE(65)] = 571,
  [SMALL_STATE(66)] = 575,
  [SMALL_STATE(67)] = 579,
  [SMALL_STATE(68)] = 583,
};

static const TSParseActionEntry ts_parse_actions[] = {
  [0] = {.entry = {.count = 0, .reusable = false}},
  [1] = {.entry = {.count = 1, .reusable = false}}, RECOVER(),
  [3] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_source_file, 0, 0, 0),
  [5] = {.entry = {.count = 1, .reusable = false}}, SHIFT(50),
  [7] = {.entry = {.count = 1, .reusable = true}}, SHIFT(14),
  [9] = {.entry = {.count = 1, .reusable = true}}, SHIFT(6),
  [11] = {.entry = {.count = 1, .reusable = true}}, SHIFT(2),
  [13] = {.entry = {.count = 1, .reusable = true}}, SHIFT(37),
  [15] = {.entry = {.count = 1, .reusable = true}}, SHIFT(50),
  [17] = {.entry = {.count = 1, .reusable = false}}, SHIFT(65),
  [19] = {.entry = {.count = 1, .reusable = true}}, SHIFT(16),
  [21] = {.entry = {.count = 1, .reusable = true}}, SHIFT(9),
  [23] = {.entry = {.count = 1, .reusable = true}}, SHIFT(5),
  [25] = {.entry = {.count = 1, .reusable = true}}, SHIFT(61),
  [27] = {.entry = {.count = 1, .reusable = true}}, SHIFT(31),
  [29] = {.entry = {.count = 1, .reusable = true}}, SHIFT(65),
  [31] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_source_file, 1, 0, 0),
  [33] = {.entry = {.count = 1, .reusable = true}}, REDUCE(aux_sym_source_file_repeat1, 2, 0, 0),
  [35] = {.entry = {.count = 2, .reusable = false}}, REDUCE(aux_sym_source_file_repeat1, 2, 0, 0), SHIFT_REPEAT(50),
  [38] = {.entry = {.count = 2, .reusable = true}}, REDUCE(aux_sym_source_file_repeat1, 2, 0, 0), SHIFT_REPEAT(14),
  [41] = {.entry = {.count = 2, .reusable = true}}, REDUCE(aux_sym_source_file_repeat1, 2, 0, 0), SHIFT_REPEAT(6),
  [44] = {.entry = {.count = 2, .reusable = true}}, REDUCE(aux_sym_source_file_repeat1, 2, 0, 0), SHIFT_REPEAT(2),
  [47] = {.entry = {.count = 2, .reusable = true}}, REDUCE(aux_sym_source_file_repeat1, 2, 0, 0), SHIFT_REPEAT(37),
  [50] = {.entry = {.count = 2, .reusable = true}}, REDUCE(aux_sym_source_file_repeat1, 2, 0, 0), SHIFT_REPEAT(50),
  [53] = {.entry = {.count = 1, .reusable = true}}, SHIFT(42),
  [55] = {.entry = {.count = 1, .reusable = false}}, SHIFT(63),
  [57] = {.entry = {.count = 1, .reusable = true}}, SHIFT(56),
  [59] = {.entry = {.count = 1, .reusable = true}}, SHIFT(63),
  [61] = {.entry = {.count = 2, .reusable = false}}, REDUCE(aux_sym_dictionary_repeat1, 2, 0, 0), SHIFT_REPEAT(65),
  [64] = {.entry = {.count = 2, .reusable = true}}, REDUCE(aux_sym_dictionary_repeat1, 2, 0, 0), SHIFT_REPEAT(16),
  [67] = {.entry = {.count = 2, .reusable = true}}, REDUCE(aux_sym_dictionary_repeat1, 2, 0, 0), SHIFT_REPEAT(9),
  [70] = {.entry = {.count = 2, .reusable = true}}, REDUCE(aux_sym_dictionary_repeat1, 2, 0, 0), SHIFT_REPEAT(5),
  [73] = {.entry = {.count = 2, .reusable = true}}, REDUCE(aux_sym_dictionary_repeat1, 2, 0, 0), SHIFT_REPEAT(31),
  [76] = {.entry = {.count = 2, .reusable = true}}, REDUCE(aux_sym_dictionary_repeat1, 2, 0, 0), SHIFT_REPEAT(65),
  [79] = {.entry = {.count = 1, .reusable = false}}, SHIFT(58),
  [81] = {.entry = {.count = 1, .reusable = true}}, SHIFT(29),
  [83] = {.entry = {.count = 1, .reusable = true}}, SHIFT(58),
  [85] = {.entry = {.count = 1, .reusable = false}}, SHIFT(62),
  [87] = {.entry = {.count = 1, .reusable = true}}, SHIFT(62),
  [89] = {.entry = {.count = 2, .reusable = false}}, REDUCE(aux_sym_array_repeat1, 2, 0, 0), SHIFT_REPEAT(66),
  [92] = {.entry = {.count = 2, .reusable = true}}, REDUCE(aux_sym_array_repeat1, 2, 0, 0), SHIFT_REPEAT(16),
  [95] = {.entry = {.count = 2, .reusable = true}}, REDUCE(aux_sym_array_repeat1, 2, 0, 0), SHIFT_REPEAT(9),
  [98] = {.entry = {.count = 2, .reusable = true}}, REDUCE(aux_sym_array_repeat1, 2, 0, 0), SHIFT_REPEAT(5),
  [101] = {.entry = {.count = 2, .reusable = true}}, REDUCE(aux_sym_array_repeat1, 2, 0, 0), SHIFT_REPEAT(31),
  [104] = {.entry = {.count = 2, .reusable = true}}, REDUCE(aux_sym_array_repeat1, 2, 0, 0), SHIFT_REPEAT(66),
  [107] = {.entry = {.count = 1, .reusable = false}}, SHIFT(48),
  [109] = {.entry = {.count = 1, .reusable = true}}, SHIFT(48),
  [111] = {.entry = {.count = 1, .reusable = false}}, SHIFT(53),
  [113] = {.entry = {.count = 1, .reusable = true}}, SHIFT(53),
  [115] = {.entry = {.count = 1, .reusable = false}}, SHIFT(52),
  [117] = {.entry = {.count = 1, .reusable = true}}, SHIFT(52),
  [119] = {.entry = {.count = 1, .reusable = false}}, SHIFT(43),
  [121] = {.entry = {.count = 1, .reusable = true}}, SHIFT(43),
  [123] = {.entry = {.count = 1, .reusable = false}}, REDUCE(aux_sym_dictionary_repeat1, 2, 0, 0),
  [125] = {.entry = {.count = 1, .reusable = true}}, REDUCE(aux_sym_dictionary_repeat1, 2, 0, 0),
  [127] = {.entry = {.count = 1, .reusable = true}}, SHIFT(33),
  [129] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym__rules, 2, 0, 0),
  [131] = {.entry = {.count = 1, .reusable = false}}, REDUCE(sym__rules, 2, 0, 0),
  [133] = {.entry = {.count = 1, .reusable = false}}, REDUCE(aux_sym_array_repeat1, 2, 0, 0),
  [135] = {.entry = {.count = 1, .reusable = true}}, REDUCE(aux_sym_array_repeat1, 2, 0, 0),
  [137] = {.entry = {.count = 1, .reusable = true}}, SHIFT(44),
  [139] = {.entry = {.count = 1, .reusable = true}}, SHIFT(45),
  [141] = {.entry = {.count = 1, .reusable = true}}, SHIFT(47),
  [143] = {.entry = {.count = 1, .reusable = true}}, SHIFT(36),
  [145] = {.entry = {.count = 1, .reusable = true}}, SHIFT(28),
  [147] = {.entry = {.count = 1, .reusable = true}}, SHIFT(51),
  [149] = {.entry = {.count = 1, .reusable = true}}, SHIFT(34),
  [151] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_dictionary, 4, 0, 0),
  [153] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_array, 2, 0, 0),
  [155] = {.entry = {.count = 1, .reusable = true}}, SHIFT(38),
  [157] = {.entry = {.count = 1, .reusable = true}}, SHIFT(32),
  [159] = {.entry = {.count = 1, .reusable = true}}, SHIFT(41),
  [161] = {.entry = {.count = 1, .reusable = true}}, SHIFT(30),
  [163] = {.entry = {.count = 1, .reusable = true}}, REDUCE(aux_sym_string_repeat1, 2, 0, 0),
  [165] = {.entry = {.count = 2, .reusable = true}}, REDUCE(aux_sym_string_repeat1, 2, 0, 0), SHIFT_REPEAT(32),
  [168] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_dictionary, 5, 0, 0),
  [170] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_array, 5, 0, 0),
  [172] = {.entry = {.count = 1, .reusable = true}}, SHIFT(60),
  [174] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_array, 4, 0, 0),
  [176] = {.entry = {.count = 1, .reusable = true}}, SHIFT(54),
  [178] = {.entry = {.count = 1, .reusable = true}}, SHIFT(35),
  [180] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_string, 3, 0, 0),
  [182] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_dictionary, 3, 0, 0),
  [184] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_array, 3, 0, 0),
  [186] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_string, 2, 0, 0),
  [188] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_dictionary, 2, 0, 0),
  [190] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_prefix_expression, 2, 0, 1),
  [192] = {.entry = {.count = 1, .reusable = false}}, REDUCE(sym_array, 5, 0, 0),
  [194] = {.entry = {.count = 1, .reusable = false}}, REDUCE(sym_array, 4, 0, 0),
  [196] = {.entry = {.count = 1, .reusable = false}}, REDUCE(sym_array, 3, 0, 0),
  [198] = {.entry = {.count = 1, .reusable = false}}, REDUCE(sym_dictionary, 5, 0, 0),
  [200] = {.entry = {.count = 1, .reusable = true}}, SHIFT(19),
  [202] = {.entry = {.count = 1, .reusable = false}}, REDUCE(sym_dictionary, 3, 0, 0),
  [204] = {.entry = {.count = 1, .reusable = true}}, SHIFT(18),
  [206] = {.entry = {.count = 1, .reusable = false}}, SHIFT(18),
  [208] = {.entry = {.count = 1, .reusable = false}}, REDUCE(sym_dictionary, 4, 0, 0),
  [210] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_dictionary_pair, 3, 0, 2),
  [212] = {.entry = {.count = 1, .reusable = false}}, REDUCE(sym_prefix_expression, 2, 0, 1),
  [214] = {.entry = {.count = 1, .reusable = false}}, REDUCE(sym_string, 2, 0, 0),
  [216] = {.entry = {.count = 1, .reusable = true}}, SHIFT(24),
  [218] = {.entry = {.count = 1, .reusable = true}}, SHIFT(49),
  [220] = {.entry = {.count = 1, .reusable = false}}, REDUCE(sym_array, 2, 0, 0),
  [222] = {.entry = {.count = 1, .reusable = true}}, SHIFT(21),
  [224] = {.entry = {.count = 1, .reusable = true}}, SHIFT(40),
  [226] = {.entry = {.count = 1, .reusable = true}}, SHIFT(22),
  [228] = {.entry = {.count = 1, .reusable = true}}, SHIFT(23),
  [230] = {.entry = {.count = 1, .reusable = true}}, SHIFT(39),
  [232] = {.entry = {.count = 1, .reusable = false}}, REDUCE(sym_string, 3, 0, 0),
  [234] = {.entry = {.count = 1, .reusable = false}}, REDUCE(sym_dictionary, 2, 0, 0),
  [236] = {.entry = {.count = 1, .reusable = true}}, SHIFT(25),
  [238] = {.entry = {.count = 1, .reusable = true}}, SHIFT(46),
  [240] = {.entry = {.count = 1, .reusable = true}}, SHIFT(20),
  [242] = {.entry = {.count = 1, .reusable = true}}, SHIFT(17),
  [244] = {.entry = {.count = 1, .reusable = true}}, SHIFT(15),
  [246] = {.entry = {.count = 1, .reusable = true}}, SHIFT(27),
  [248] = {.entry = {.count = 1, .reusable = true}}, SHIFT(26),
  [250] = {.entry = {.count = 1, .reusable = true}},  ACCEPT_INPUT(),
};

#ifdef __cplusplus
extern "C" {
#endif
#ifdef TREE_SITTER_HIDE_SYMBOLS
#define TS_PUBLIC
#elif defined(_WIN32)
#define TS_PUBLIC __declspec(dllexport)
#else
#define TS_PUBLIC __attribute__((visibility("default")))
#endif

TS_PUBLIC const TSLanguage *tree_sitter_aoc(void) {
  static const TSLanguage language = {
    .version = LANGUAGE_VERSION,
    .symbol_count = SYMBOL_COUNT,
    .alias_count = ALIAS_COUNT,
    .token_count = TOKEN_COUNT,
    .external_token_count = EXTERNAL_TOKEN_COUNT,
    .state_count = STATE_COUNT,
    .large_state_count = LARGE_STATE_COUNT,
    .production_id_count = PRODUCTION_ID_COUNT,
    .field_count = FIELD_COUNT,
    .max_alias_sequence_length = MAX_ALIAS_SEQUENCE_LENGTH,
    .parse_table = &ts_parse_table[0][0],
    .small_parse_table = ts_small_parse_table,
    .small_parse_table_map = ts_small_parse_table_map,
    .parse_actions = ts_parse_actions,
    .symbol_names = ts_symbol_names,
    .field_names = ts_field_names,
    .field_map_slices = ts_field_map_slices,
    .field_map_entries = ts_field_map_entries,
    .symbol_metadata = ts_symbol_metadata,
    .public_symbol_map = ts_symbol_map,
    .alias_map = ts_non_terminal_alias_map,
    .alias_sequences = &ts_alias_sequences[0][0],
    .lex_modes = ts_lex_modes,
    .lex_fn = ts_lex,
    .keyword_lex_fn = ts_lex_keywords,
    .keyword_capture_token = sym_identifier,
    .primary_state_ids = ts_primary_state_ids,
  };
  return &language;
}
#ifdef __cplusplus
}
#endif
